### PR TITLE
Updated protobuf dependency and fixed type clash

### PR DESCRIPTION
**Pull request by PlamenHristov**
## Description:
The following PR fixes protobuf name clashes, due to lack of namepsacing for `ecdsa` and `eddsa` messages.
As a side effect it also fixes issue: https://github.com/binance-chain/tss-lib/issues/106

## Work done: 

- Removed deprecated `github.com/golang/protobuf` dependency
- Added namepsacing to ecdsa and eddsa message types, to avoid name clash
- Updated Go version to 1.16

## Requested reviewers:
@ackratos, @omershlo , @notatestuser 
(tagging like that, since I don't seem to be allowed to request review the normal way)

### CODE REVIEW

**Review by yycen — COMMENTED** [review]
Solved issue #106. No conflicts.

**Review by yycen — APPROVED** [review]

**Comment by yycen** [comment]
@PlamenHristov We have update the master branch. It still has deprecated package usage. Would you like to do a rebase to your PR?

**Comment by PlamenHristov** [comment]
Hey @yycen,

Merged from master and resolved conflicts.

**Comment by yycen** [comment]
The file signature.pb.go has not been regenerated and still references github.com/golang/protobuf/proto. Would you update signature.proto file with go_package = "./common" and regenerate to pb file?

**Comment by PlamenHristov** [comment]
Ah apologies. Was doing the update in a rush and missed it. 
Should be good now.

**Review by yycen — APPROVED** [review]

**Review by ackratos — APPROVED** [review]

**Pull request merged**
